create unique index IDX_CES_STAFF_POSISTION_UNIQ_POS_ID on CES_STAFF_POSISTION (POS_ID) where DELETE_TS is null ;
create unique index IDX_CES_STAFF_POSISTION_UNIQ_POS_NAME on CES_STAFF_POSISTION (POS_NAME) where DELETE_TS is null ;
